{
  "openapi": "3.0.0",
  "info": {
    "title": "Live Changes API",
    "version": "1.0",
    "description": "This is a draft introduction.",
    "contact": {
      "name": "NaveenKumar Namachivayam",
      "email": "catch.nkn@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:7566",
      "description": "Live Changes API"
    }
  ],
  "paths": {
    "/api/threads/{thread-group-name}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "thread-group-name",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "GET Thread",
        "tags": [
          "get",
          "threads"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "success-response": {
                    "value": {
                      "getOnErrorStartNextLoop": false,
                      "getOnErrorStopTest": false,
                      "scheduler": {
                        "duration": 600,
                        "delay": 0
                      },
                      "getOnErrorStopTestNow": false,
                      "getOnErrorStopThread": false,
                      "isEnabled": true,
                      "name": "Thread Group",
                      "active": 1,
                      "comment": "",
                      "rampUp": 1
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-threads-name",
        "description": "Retrieves information about a specific thread group.",
        "parameters": []
      }
    },
    "/api/threads": {
      "get": {
        "summary": "GET All Threads",
        "tags": [
          "get",
          "threads"
        ],
        "operationId": "get-api-threads",
        "description": "Retrieves information about all thread groups",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "format": "hostname",
                  "default": "localhost",
                  "deprecated": false
                },
                "description": "test",
                "allowEmptyValue": false,
                "allowReserved": false
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "success-response": {
                    "value": [
                      {
                        "getOnErrorStartNextLoop": false,
                        "getOnErrorStopTest": false,
                        "getOnErrorStopTestNow": false,
                        "getOnErrorStopThread": false,
                        "isEnabled": true,
                        "name": "Thread Group",
                        "active": 0,
                        "comment": "",
                        "rampUp": 1
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "test",
            "description": ""
          }
        ]
      }
    },
    "/api/variables": {
      "get": {
        "summary": "GET Variables",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "success-response": {
                    "value": {
                      "START.MS": "1591110191950",
                      "TESTSTART.MS": "1591113928254",
                      "JMeterThread.last_sample_ok": "true",
                      "__jm__Thread Group__idx": "1490",
                      "__jmeter.U_T__": "Thread Group 1-1",
                      "START.HMS": "110311",
                      "JMeterThread.pack": "org.apache.jmeter.threads.SamplePackage@37e9db3d",
                      "__jmv_SAME_USER": "true",
                      "START.YMD": "20200602"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-variables"
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}